### ISSUE TITLE
Python bluetooth socket error

### ISSUE THREAD

**Issue by Hyejinini** [BITalinoWorld/revolution-python-api#11]
Hello. I hope you're doing well and safe. I am contacting you because I have a question about this code. 

I think it's an error in the Bluetooth socket part, but I'm not sure why this the error occurs. 
As you can see from the attached photo, it was confirmed that the bitalino device could not be connected due to an error in parts " self.socket = bluetooth.BluetoothSocket(bluetooth.RFCOMM) " and "Class BluetoothSocket ".

I am sending you a question to ask which part to check because there is no error if you run the 'Class BluetoothSocket' part code separately. 

What part do I have to check? I'd like to hear your valuable opinion. 
I'm afraid my lack of English will interfere with your understanding. 
Happy New Year, though late, and I hope your day is happy. 

I'll be waiting for your reply. 
Thank you. 

![2](https://user-images.githubusercontent.com/99716955/154016201-2ab8d4d9-fd16-4349-94e9-26709ac100dc.JPG)
![self socket](https://user-images.githubusercontent.com/99716955/154016219-5f77a0d6-533d-4a1c-8d8f-03e00049b765.JPG)
![proto](https://user-images.githubusercontent.com/99716955/154016227-e804a7ff-b8db-4a59-8cb5-9aa3bcf19a18.JPG)

**Comment by fcachado** [comment]
Hello @Hyejinini,

In order to fix your issue you should uninstall the Pybluez package that you have installed in your machine, and then install it using the following command:
`pip install git+https://github.com/pybluez/pybluez.git`

Also, you should run this package with Python between 3.7 and 3.10, which are the versions that we assure compatibility.

I hope this answer can help you fix the issue.

**Comment by Hyejinini** [comment]
Hello.

I really appreciate your kind reply.
Thanks to you, I solved the problem well.

I hope your day will be happy. Thank you :)
